name: Clone

on:
  workflow_call:
    inputs:
      build-id:
        type: string
        default: 'master'
      submodules:
        type: string
        default: 'true'

runs:
  using: "composite"
  steps:
    - name: Parse Forgejo payload
      uses: ./.github/workflows/parse
      with:
        build-id: ${{ inputs.build-id }}

    - name: Checkout Repo
      shell: bash
      run: |

        while ! git clone $FORGEJO_CLONE_URL eden; do
          echo "Clone failed!"
          sleep 5
          echo "Trying clone again..."
          rm -rf ./eden || true
        done

        cd eden
        git reset --hard $FORGEJO_REF

    - name: Update submodules
      if: inputs.submodules == 'true'
      shell: bash
      run: |
        cd eden
        git submodule update --init --recursive