name: Get Variables

on:
  workflow_call:
    inputs:
      build-id:
        type: string
        default: 'master'

runs:
  using: "composite"
  steps:
    - name: Parse Forgejo payload
      shell: bash
      run: |
        export PAYLOAD_JSON='${{ toJSON(github.event.client_payload) }}'
        export FORGEJO_TOKEN=${{ secrets.FORGEJO_TOKEN }}
        ./.ci/parse.sh ${{ inputs.build-id }}