name: ".deb builds"

on:
  workflow_call:
    inputs:
      build-id:
        description: "build id"
        type: string
        required: true
      cpm-cache-version:
        description: "CPM cache version (e.g. v7)"
        type: string
        required: true
      devel:
        description: 'development build'
        type: string
        required: true

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}

jobs:
  # set-matrix:
  #   name: "Generate Debian Matrix"
  #   runs-on: ubuntu-latest
  #   outputs:
  #     matrix: ${{ steps.set.outputs.matrix }}
  #     compiler: ${{ steps.set.outputs.compiler }}
  #   steps:
  #     - id: set
  #       run: |
  #         BASE='[{"runs-on": "ubuntu-24.04", "arch": "amd64"}'
  #         ARM=',{"runs-on": "ubuntu-24.04-arm", "arch": "aarch64"}]'

  #         if [ "${{ inputs.build-id }}" = "tag" ]; then
  #           MATRIX="${BASE}${ARM}"
  #         else
  #           MATRIX="${BASE}]"
  #         fi

  #         echo $MATRIX
  #         echo "matrix=${MATRIX}" >> $GITHUB_OUTPUT

  ubuntu:
    name: "Ubuntu 24.04 (${{ matrix.os.arch }})"
    runs-on: ${{ matrix.os.runs-on }}
    # needs: [set-matrix]
    strategy:
      fail-fast: false
      # matrix:
      #   os: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
      matrix:
        os: >-
          ${{ fromJson(format(
            '[{"runs-on": "ubuntu-24.04", "arch": "amd64"}{0}]',
            (github.ref_type == 'tag' && ',{"runs-on": "ubuntu-24.04-arm", "arch": "aarch64"}') || ''
          )) }}


    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Build & Package
        uses: ./.github/workflows/debian
        with:
          arch: ${{ matrix.os.arch }}
          name: ubuntu-24.04
          cpm-cache-version: ${{ inputs.cpm-cache-version }}
          devel: ${{ inputs.devel }}

  debian-13:
    name: "Debian 13 (${{ matrix.os.arch }})"
    runs-on: ${{ matrix.os.runs-on }}
    container: ghcr.io/nilcons/debian:latest
    strategy:
      fail-fast: false
      matrix:
        os: >-
          ${{ fromJson(format(
            '[{"runs-on": "ubuntu-24.04", "arch": "amd64"}{0}]',
            (github.ref_type == 'tag' && ',{"runs-on": "ubuntu-24.04-arm", "arch": "aarch64"}') || ''
          )) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Build & Package
        uses: ./.github/workflows/debian
        with:
          arch: ${{ matrix.os.arch }}
          name: debian-13
          cpm-cache-version: ${{ inputs.cpm-cache-version }}
          devel: ${{ inputs.devel }}

  debian-12:
    name: "Debian 12 (${{ matrix.os.arch }})"
    runs-on: ${{ matrix.os.runs-on }}
    container: ghcr.io/xrplf/ci/debian-bookworm:gcc-12
    strategy:
      fail-fast: false
      matrix:
        os: >-
          ${{ fromJson(format(
            '[{"runs-on": "ubuntu-24.04", "arch": "amd64"}{0}]',
            (github.ref_type == 'tag' && ',{"runs-on": "ubuntu-24.04-arm", "arch": "aarch64"}') || ''
          )) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Build & Package
        uses: ./.github/workflows/debian
        with:
          arch: ${{ matrix.os.arch }}
          name: debian-12
          cpm-cache-version: ${{ inputs.cpm-cache-version }}
          devel: ${{ inputs.devel }}

