name: "[Internal CI] Windows"

on:
  workflow_call:
    inputs:
      build-id:
        description: "build id"
        type: string
        required: true
      cpm-cache-version:
        description: "CPM cache version (e.g. v7)"
        type: string
        required: true
      devel:
        description: 'development build'
        type: string
        required: true

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}

jobs:
  win-matrix:
    name: "Generate Windows compilers"
    runs-on: ubuntu-latest
    outputs:
      compiler: ${{ steps.set.outputs.compiler }}
    steps:
      - id: set
        run: |
          PGO='{"program": "clang", "target": "pgo"}'
          CLANG='{"program": "clang", "target": "standard"}'
          MSVC='{"program": "msvc", "target": "standard"}'
          MINGW='{"program": "mingw", "target": "standard"}'

          if [ "${{ inputs.build-id }}" = "tag" ]; then
            COMPILER="[${MSVC},${CLANG},${PGO},${MINGW}]"
          else
            COMPILER="[${MSVC},${CLANG},${MINGW}]"
          fi

          echo $COMPILER
          echo "compiler=${COMPILER}" >> $GITHUB_OUTPUT

  windows:
    name: "Windows ${{ matrix.os.arch }} ${{ matrix.compiler.program }} ${{ matrix.compiler.target }}"
    needs: [win-matrix]
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runs-on: windows-latest
            arch: amd64
            sys: mingw64
            env: x86_64
          - runs-on: windows-11-arm
            arch: arm64
            sys: clangarm64
            env: clang-aarch64
        compiler: ${{ fromJson(needs.win-matrix.outputs.compiler) }}

    env:
      QT_VERSION: 6.9.1
      TARGET: ${{ matrix.os.arch }}
      COMPILER: "${{ matrix.compiler.program }}"
      PGO_TARGET: "${{ matrix.compiler.target }}"
      ARCH: ${{ matrix.os.arch }}-${{ matrix.compiler.program }}-${{ matrix.compiler.target }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          key: ${{ runner.os }}-${{ matrix.os.arch }}-${{ matrix.compiler.program }}
          version: ${{ inputs.cpm-cache-version }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.3.0
        with:
          version: ${{ env.QT_VERSION }}
          cache: 'true'

      - name: Load payload environment
        shell: bash
        run: |
          . ./.ci/common/load-env.sh --load-payload-env

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: ${{ matrix.os.arch }}

      - name: Install MSYS2 environment
        if: matrix.compiler.program == 'mingw'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.os.sys}}
          install: >-
            git
            dos2unix

      - name: Install necessary MINGW packages
        if: matrix.compiler.program == 'mingw'
        shell: msys2 {0}
        run: |
          #TODO: Adapt to allow clang-aarch64
          git clone https://git.crueter.xyz/scripts/windev.git .windev
          cd .windev
          ./install.sh -d || true
          ./install.sh -d || true

      - name: Force Clang 20
        if: matrix.compiler.program == 'clang'
        shell: bash
        run: |
          echo "C:/Program Files/LLVM/bin" >> $GITHUB_PATH
          clang-cl --version

      - name: Install Vulkan SDK
        shell: powershell
        run: |
          ./.ci/windows/install-vulkan-sdk.ps1

      - name: Configure
        if: matrix.compiler.program == 'mingw'
        shell: msys2 {0}
        run: |
          git config --global core.autocrlf off
          dos2unix .patch/boost/*
          .ci/common/configure.sh -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Configure
        if: matrix.compiler.program != 'mingw'
        shell: bash
        run: |
          git config --global core.autocrlf off
          dos2unix .patch/boost/*
          .ci/common/configure.sh -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Build
        if: matrix.compiler.program == 'mingw'
        shell: msys2 {0}
        run: cmake --build build

      - name: Build
        if: matrix.compiler.program != 'mingw'
        shell: bash
        run: cmake --build build

      - name: Package
        if: matrix.compiler.program == 'mingw'
        shell: msys2 {0}
        run: ./.ci/windows/package.sh

      - name: Package
        if: matrix.compiler.program != 'mingw'
        shell: bash
        run: ./.ci/windows/package.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: windows-${{ env.ARCH }}
          path: artifacts/*

